controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check
    methods: [POST]
    controller: App\Api\NewsController::all

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.app.home:
    path: /
    controller: App\Controller\AppController::index

app.app.front:
    path: /app/{url<.*>}
    controller: App\Controller\AppController::index